import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.user.createMany({
    data: [
      { email: 'sample1.com', name: 'user1' },
      { email: 'sample2.com', name: 'user2' },
      { email: 'sample3.com', name: 'user3' },
      { email: 'sample4.com', name: 'user4' },
      { email: 'sample5.com', name: 'user5' },
      { email: 'sample6.com', name: 'user6' },
      { email: 'sample7.com', name: 'user7' },
      { email: 'sample8.com', name: 'user8' },
      { email: 'sample9.com', name: 'user9' },
      { email: 'sample10.com', name: 'user10' },
      { email: 'sample11.com', name: 'user11' },
      { email: 'sample12.com', name: 'user12' },
      { email: 'sample13.com', name: 'user13' },
      { email: 'sample14.com', name: 'user14' },
      { email: 'sample15.com', name: 'user15' },
    ],
  });

  await prisma.category.createMany({
    data: [
      { name: '給与' },
      { name: '副業収入' },
      { name: '配当' },
      { name: '臨時収入' },
      { name: '食費' },
      { name: '家賃' },
      { name: '光熱費' },
      { name: '交際費' },
      { name: '衣料' },
      { name: '医療費' },
      { name: '投資' },
      { name: '日用品' },
      { name: '税金' },
      { name: '交通費' },
      { name: '雑費' },
      { name: '固定費' },
      { name: 'サブスクリプション' },
      { name: '通信費' },
    ],
  });
  await prisma.expenseItem.createMany({
    data: [
      { name: '給与' },
      { name: '副業' },
      { name: '株式配当金' },
      { name: '外食' },
      { name: '家賃' },
      { name: '水道代' },
      { name: '電気代' },
      { name: 'ガス代' },
      { name: '食費' },
      { name: '日用品' },
      { name: '交際費' },
      { name: '交通費' },
      { name: '雑費' },
      { name: '医療費' },
      { name: '旅費' },
      { name: 'スマホ代' },
      { name: 'ネット代' },
    ],
  });
  await prisma.moneyDiary.createMany({
    data: moneyDiaries,
  });
  await prisma.moneyDiary_Category.createMany({
    data: [
      { moneyDiaryId: 1, categoryId: 1 },
      { moneyDiaryId: 2, categoryId: 2 },
      { moneyDiaryId: 3, categoryId: 6 },
      { moneyDiaryId: 4, categoryId: 7 },
      { moneyDiaryId: 5, categoryId: 7 },
      { moneyDiaryId: 6, categoryId: 15 },
      { moneyDiaryId: 7, categoryId: 5 },
      { moneyDiaryId: 8, categoryId: 16 },
      { moneyDiaryId: 8, categoryId: 17 },
      { moneyDiaryId: 9, categoryId: 10 },
      { moneyDiaryId: 10, categoryId: 7 },
      { moneyDiaryId: 11, categoryId: 18 },
      { moneyDiaryId: 1 + 11, categoryId: 1 },
      { moneyDiaryId: 2 + 11, categoryId: 2 },
      { moneyDiaryId: 3 + 11, categoryId: 6 },
      { moneyDiaryId: 4 + 11, categoryId: 7 },
      { moneyDiaryId: 5 + 11, categoryId: 7 },
      { moneyDiaryId: 6 + 11, categoryId: 15 },
      { moneyDiaryId: 7 + 11, categoryId: 5 },
      { moneyDiaryId: 8 + 11, categoryId: 16 },
      { moneyDiaryId: 8 + 11, categoryId: 17 },
      { moneyDiaryId: 9 + 11, categoryId: 10 },
      { moneyDiaryId: 10 + 11, categoryId: 7 },
      { moneyDiaryId: 11 + 11, categoryId: 18 },
      { moneyDiaryId: 1 + 22, categoryId: 1 },
      { moneyDiaryId: 2 + 22, categoryId: 2 },
      { moneyDiaryId: 3 + 22, categoryId: 6 },
      { moneyDiaryId: 4 + 22, categoryId: 7 },
      { moneyDiaryId: 5 + 22, categoryId: 7 },
      { moneyDiaryId: 6 + 22, categoryId: 15 },
      { moneyDiaryId: 7 + 22, categoryId: 5 },
      { moneyDiaryId: 8 + 22, categoryId: 16 },
      { moneyDiaryId: 8 + 22, categoryId: 17 },
      { moneyDiaryId: 9 + 22, categoryId: 10 },
      { moneyDiaryId: 10 + 22, categoryId: 7 },
      { moneyDiaryId: 11 + 22, categoryId: 18 },
      { moneyDiaryId: 1 + 33, categoryId: 1 },
      { moneyDiaryId: 2 + 33, categoryId: 2 },
      { moneyDiaryId: 3 + 33, categoryId: 6 },
      { moneyDiaryId: 4 + 33, categoryId: 7 },
      { moneyDiaryId: 5 + 33, categoryId: 7 },
      { moneyDiaryId: 6 + 33, categoryId: 15 },
      { moneyDiaryId: 7 + 33, categoryId: 5 },
      { moneyDiaryId: 8 + 33, categoryId: 16 },
      { moneyDiaryId: 8 + 33, categoryId: 17 },
      { moneyDiaryId: 9 + 33, categoryId: 10 },
      { moneyDiaryId: 10 + 33, categoryId: 7 },
      { moneyDiaryId: 11 + 33, categoryId: 18 },
      { moneyDiaryId: 1 + 44, categoryId: 1 },
      { moneyDiaryId: 2 + 44, categoryId: 2 },
      { moneyDiaryId: 3 + 44, categoryId: 6 },
      { moneyDiaryId: 4 + 44, categoryId: 7 },
      { moneyDiaryId: 5 + 44, categoryId: 7 },
      { moneyDiaryId: 6 + 44, categoryId: 15 },
      { moneyDiaryId: 7 + 44, categoryId: 5 },
      { moneyDiaryId: 8 + 44, categoryId: 16 },
      { moneyDiaryId: 8 + 44, categoryId: 17 },
      { moneyDiaryId: 9 + 44, categoryId: 10 },
      { moneyDiaryId: 10 + 44, categoryId: 7 },
      { moneyDiaryId: 11 + 44, categoryId: 18 },
      { moneyDiaryId: 1 + 55, categoryId: 1 },
      { moneyDiaryId: 2 + 55, categoryId: 2 },
      { moneyDiaryId: 3 + 55, categoryId: 6 },
      { moneyDiaryId: 4 + 55, categoryId: 7 },
      { moneyDiaryId: 5 + 55, categoryId: 7 },
      { moneyDiaryId: 6 + 55, categoryId: 15 },
      { moneyDiaryId: 7 + 55, categoryId: 5 },
      { moneyDiaryId: 8 + 55, categoryId: 16 },
      { moneyDiaryId: 8 + 55, categoryId: 17 },
      { moneyDiaryId: 9 + 55, categoryId: 10 },
      { moneyDiaryId: 10 + 55, categoryId: 7 },
      { moneyDiaryId: 11 + 55, categoryId: 18 },
      { moneyDiaryId: 1 + 66, categoryId: 1 },
      { moneyDiaryId: 2 + 66, categoryId: 2 },
      { moneyDiaryId: 3 + 66, categoryId: 6 },
      { moneyDiaryId: 4 + 66, categoryId: 7 },
      { moneyDiaryId: 5 + 66, categoryId: 7 },
      { moneyDiaryId: 6 + 66, categoryId: 15 },
      { moneyDiaryId: 7 + 66, categoryId: 5 },
      { moneyDiaryId: 8 + 66, categoryId: 16 },
      { moneyDiaryId: 8 + 66, categoryId: 17 },
      { moneyDiaryId: 9 + 66, categoryId: 10 },
      { moneyDiaryId: 10 + 66, categoryId: 7 },
      { moneyDiaryId: 11 + 66, categoryId: 18 },
      { moneyDiaryId: 1 + 77, categoryId: 1 },
      { moneyDiaryId: 2 + 77, categoryId: 2 },
      { moneyDiaryId: 3 + 77, categoryId: 6 },
      { moneyDiaryId: 4 + 77, categoryId: 7 },
      { moneyDiaryId: 5 + 77, categoryId: 7 },
      { moneyDiaryId: 6 + 77, categoryId: 15 },
      { moneyDiaryId: 7 + 77, categoryId: 5 },
      { moneyDiaryId: 8 + 77, categoryId: 16 },
      { moneyDiaryId: 8 + 77, categoryId: 17 },
      { moneyDiaryId: 9 + 77, categoryId: 10 },
      { moneyDiaryId: 10 + 77, categoryId: 7 },
      { moneyDiaryId: 11 + 77, categoryId: 18 },
      { moneyDiaryId: 1 + 88, categoryId: 1 },
      { moneyDiaryId: 2 + 88, categoryId: 2 },
      { moneyDiaryId: 3 + 88, categoryId: 6 },
      { moneyDiaryId: 4 + 88, categoryId: 7 },
      { moneyDiaryId: 5 + 88, categoryId: 7 },
      { moneyDiaryId: 6 + 88, categoryId: 15 },
      { moneyDiaryId: 7 + 88, categoryId: 5 },
      { moneyDiaryId: 8 + 88, categoryId: 16 },
      { moneyDiaryId: 8 + 88, categoryId: 17 },
      { moneyDiaryId: 9 + 88, categoryId: 10 },
      { moneyDiaryId: 10 + 88, categoryId: 7 },
      { moneyDiaryId: 11 + 88, categoryId: 18 },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });

const moneyDiaries = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  .map((month) => {
    return [
      {
        memo: '残業20H',
        withdrawal: 300000,
        payment: 0,
        date: new Date(`2021-${month}-025`),
        period: 0,
        userId: 1,
        expenseItemName: `${month}月給料`,
      },
      {
        memo: '20H稼働',
        withdrawal: 50000,
        payment: 0,
        date: new Date(`2021-${month}-025`),
        period: 0,
        userId: 1,
        expenseItemName: 'React副業',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 90000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '家賃',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 5000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '水道代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 8000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '電気代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 3000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'スマホ代',
      },
      {
        memo: 'やよい軒',
        withdrawal: 0,
        payment: 1000,
        date: new Date(`2021-${month}-10`),
        period: 0,
        userId: 1,
        expenseItemName: 'ランチ代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 1500,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'YouTubeサブスク',
      },
      {
        memo: '皮膚科',
        withdrawal: 0,
        payment: 1000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '病院代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 3000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'ガス代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 4000,
        date: new Date(`2021-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'ネット代',
      },
      // -----------------
      {
        memo: '残業20H',
        withdrawal: 300000,
        payment: 0,
        date: new Date(`2022-${month}-025`),
        period: 0,
        userId: 1,
        expenseItemName: `${month}月給料`,
      },
      {
        memo: '20H稼働',
        withdrawal: 50000,
        payment: 0,
        date: new Date(`2022-${month}-025`),
        period: 0,
        userId: 1,
        expenseItemName: 'React副業',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 90000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '家賃',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 5000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '水道代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 8000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '電気代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 3000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'スマホ代',
      },
      {
        memo: 'やよい軒',
        withdrawal: 0,
        payment: 1000,
        date: new Date(`2022-${month}-10`),
        period: 0,
        userId: 1,
        expenseItemName: 'ランチ代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 1500,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'YouTubeサブスク',
      },
      {
        memo: '皮膚科',
        withdrawal: 0,
        payment: 1000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: '病院代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 3000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'ガス代',
      },
      {
        memo: '',
        withdrawal: 0,
        payment: 4000,
        date: new Date(`2022-${month}-027`),
        period: 0,
        userId: 1,
        expenseItemName: 'ネット代',
      },
    ];
  })
  .flat();
